Nexters/Bottles_Android

core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/topbars/TopBar.kt

close: #13 
포넌트 TopBar 구현했는데 어렵네요..! 
이 3번째 케이스 해결을 못했는데 어떻게 하면 좋을까요?
일단 component가 뭔지, Preview는 왜 쓰는건지는 알게됐습니다!

[Feat] 컴포넌트 TopBar 구현

---

core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/etc/chips/Chip.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/etc/chips/Progress.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/etc/chips/Text.kt

[Feat] 다자인 시스템  - etc 컴포넌트 chip

---

core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/buttons/SolidButton.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/textfield/LineTextField.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/textfield/LinesTextField.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/textfield/TextField.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/textfield/TextFieldErrorCaption.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/textfield/TextFieldState.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/foundation/Color.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/foundation/Padding.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/theme/BottlesColor.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/theme/BottlesPadding.kt

- #5 
- TextFieldWithTrailingIcon, TextFieldWithTrailingButton 구현

[Feat] 디자인 시스템 - TextField 컴포넌트 구현

---

core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/buttons/DropDownButton.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/etc/chips/Progress.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/textfield/LinesTextField.kt

- #5 
- Drop Down Button 2종 구현

[Feat] 디자인 시스템 - Drop Down Button 컴포넌트 구현

---

core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/buttons/SolidButton.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/popup/BalloonPopup.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/textfield/LinesTextField.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/util/BottlesIcons.kt
core/design-system/src/main/res/drawable/ic_balloon_vertex_10_6.xml

- #5 
- BottlesBalloonPopup 2종 구현

[Feat] 디자인 시스템 - Popup 컴포넌트 구현

---

core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/bars/NavBar.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/buttons/DropDownButton.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/buttons/OutlinedButton.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/buttons/SolidButton.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/etc/chips/Progress.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/etc/chips/Text.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/etc/menu/BottomNavItem.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/popup/BalloonPopup.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/textfield/LineTextField.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/textfield/LinesTextField.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/theme/BottlesPadding.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/theme/BottlesShape.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/theme/BottlesSpacing.kt
core/ui/src/main/kotlin/com/team/bottles/core/ui/CardProfile.kt
core/ui/src/main/kotlin/com/team/bottles/core/ui/UserProfileItem.kt
feat/login/src/main/kotlin/com/team/bottles/feat/login/LoginScreen.kt
feat/login/src/main/kotlin/com/team/bottles/feat/login/component/KakaoLoginButton.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/IntroductionScreen.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/component/SelecteImage.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/component/Title.kt

- padding, spacing, shape 피그마 처럼 사이즈로 분류

[Fix] 디자인 시스템 Spacing 네이밍 변경

---

app/src/main/java/com/team/bottles/di/repository/RepositoryModule.kt
app/src/main/java/com/team/bottles/di/usecase/AuthUseCaseModule.kt
app/src/main/java/com/team/bottles/di/usecase/BottleUseCaseModule.kt
app/src/main/java/com/team/bottles/di/usecase/ProfileUseCaseModule.kt
app/src/main/java/com/team/bottles/navigation/BottlesNavHost.kt
core/data/src/main/kotlin/com/team/bottles/core/data/mapper/KakaoSignInUpResponseMapper.kt
core/data/src/main/kotlin/com/team/bottles/core/data/mapper/PingPongListResponseMapper.kt
core/data/src/main/kotlin/com/team/bottles/core/data/repository/BottleRepositoryImpl.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/auth/model/AuthResult.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/model/PingPongBottle.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/repository/BottleRepository.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/usecase/GetPingPongListUseCase.kt
core/navigator/src/main/kotlin/BottleNavigator.kt
core/network/src/main/kotlin/com/team/bottles/network/api/BottleService.kt
core/network/src/main/kotlin/com/team/bottles/network/api/ProfileService.kt
core/network/src/main/kotlin/com/team/bottles/network/datasource/BottleDataSource.kt
core/network/src/main/kotlin/com/team/bottles/network/datasource/BottleDataSourceImpl.kt
core/network/src/main/kotlin/com/team/bottles/network/di/RemoteDataSourceModule.kt
core/network/src/main/kotlin/com/team/bottles/network/di/ServiceModule.kt
core/network/src/main/kotlin/com/team/bottles/network/dto/auth/response/KakaoSignInUpResponse.kt
core/network/src/main/kotlin/com/team/bottles/network/dto/bottle/reponse/PingPongListResponse.kt
core/network/src/main/kotlin/com/team/bottles/network/dto/profile/reponse/PingPongListResponse.kt
core/ui/src/main/kotlin/com/team/bottles/core/ui/model/Bottle.kt
feat/bottle/src/main/kotlin/com/team/bottles/feat/bottle/bottlebox/BottleBoxRoute.kt
feat/bottle/src/main/kotlin/com/team/bottles/feat/bottle/bottlebox/BottleBoxViewModel.kt
feat/bottle/src/main/kotlin/com/team/bottles/feat/bottle/bottlebox/mvi/BottleBoxSideEffect.kt
feat/bottle/src/main/kotlin/com/team/bottles/feat/bottle/navigation/BottleNavigation.kt

- #29 
- 보틀 보관함 기능 구현
- 보틀 보관함 탭 클릭 시 핑퐁 리스트 가져오기 구현
- 대화중, 완료 탭 클릭 시 핑퐁 리스트 가져오기 구현
- KakaoSignInUpResponse에 `hasCompleteIntroduction: Boolean` 데이터 추가

[Feat] 보틀 보관함 기능 구현

---

app/src/main/java/com/team/bottles/di/usecase/BottleUseCaseModule.kt
core/data/src/main/kotlin/com/team/bottles/core/data/mapper/BottlePingPongResponseMapper.kt
core/data/src/main/kotlin/com/team/bottles/core/data/mapper/PingPongListResponseMapper.kt
core/data/src/main/kotlin/com/team/bottles/core/data/repository/BottleRepositoryImpl.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/model/PingPongBottle.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/model/PingPongDetail.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/model/PingPongMatchResult.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/model/PingPongPhoto.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/repository/BottleRepository.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/usecase/GetPingPongDetailUseCase.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/usecase/GetPingPongListUseCase.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/usecase/SelectPingPongShareKakaoIdUseCase.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/usecase/SelectPingPongSharePhotoUseCase.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/usecase/SendPingPongLetterUseCase.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/bottle/usecase/StopPingPongUseCase.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/profile/model/UserProfile.kt
core/network/src/main/kotlin/com/team/bottles/network/api/BottleService.kt
core/network/src/main/kotlin/com/team/bottles/network/datasource/BottleDataSource.kt
core/network/src/main/kotlin/com/team/bottles/network/datasource/BottleDataSourceImpl.kt
core/network/src/main/kotlin/com/team/bottles/network/dto/bottle/reponse/BottlePingPongResponse.kt
core/network/src/main/kotlin/com/team/bottles/network/dto/bottle/request/BottleImageShareRequest.kt
core/network/src/main/kotlin/com/team/bottles/network/dto/bottle/request/BottleMatchRequest.kt
core/network/src/main/kotlin/com/team/bottles/network/dto/bottle/request/RegisterLetterRequest.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/PingPongScreen.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/PingPongViewModel.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/components/KakaoShareCard.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/components/PingPongContents.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/components/Topbar.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/mvi/PingPongUiState.kt

- #29 
- 핑퐁 조회하기 기능 구현
- 사진 공유 선택 기능 구현
- 편지 답변 기능 구현
- 최종 선택 기능 구현
- 보틀 읽음 표시 기능 구현
- 대화 중단 기능 구현

[Feat] 핑퐁 화면 기능 구현

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/team/bottles/client/KakaoClientImpl.kt
app/src/main/java/com/team/bottles/di/usecase/ProfileUseCaseModule.kt
app/src/main/java/com/team/bottles/navigation/BottlesNavHost.kt
core/data/src/main/kotlin/com/team/bottles/core/data/mapper/UserProfileStatusResponseMapper.kt
core/data/src/main/kotlin/com/team/bottles/core/data/repository/ProfileRepositoryImpl.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/profile/model/UserProfileStatus.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/profile/repository/ProfileRepository.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/profile/usecase/GetUserProfileStatusUseCase.kt
core/network/src/main/kotlin/com/team/bottles/network/api/ProfileService.kt
core/network/src/main/kotlin/com/team/bottles/network/datasource/ProfileDataSource.kt
core/network/src/main/kotlin/com/team/bottles/network/datasource/ProfileDataSourceImpl.kt
core/network/src/main/kotlin/com/team/bottles/network/dto/profile/reponse/UserProfileStatusResponse.kt
feat/login/src/main/kotlin/com/team/bottles/feat/login/LoginRoute.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/IntroductionRoute.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/IntroductionScreen.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/IntroductionViewModel.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/mvi/IntroductionSideEffect.kt
feat/report/src/main/kotlin/com/team/bottles/feat/report/ReportScreen.kt
feat/report/src/main/kotlin/com/team/bottles/feat/report/ReportViewModel.kt
feat/sandbeach/src/main/kotlin/com/team/bottles/feat/sandbeach/SandBeachViewModel.kt
feat/splash/src/main/kotlin/com/team/bottles/feat/splash/SplashNavigation.kt
feat/splash/src/main/kotlin/com/team/bottles/feat/splash/SplashRoute.kt
feat/splash/src/main/kotlin/com/team/bottles/feat/splash/SplashSideEffect.kt
feat/splash/src/main/kotlin/com/team/bottles/feat/splash/SplashViewModel.kt
gradle/libs.versions.toml

[Release] 0.9.0-beta

---

app/.gitignore
app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

- google-services.json 파일 추가
- firebase-bom 빌드 설정
- 앱 무결성 체크 설정

[Feat] Google Services 추가

---

core/design-system/build.gradle.kts
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/etc/UserInfo.kt
core/ui/src/main/kotlin/com/team/bottles/core/ui/BottleItem.kt
core/ui/src/main/kotlin/com/team/bottles/core/ui/BottleList.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/IntroductionScreen.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/IntroductionViewModel.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/mvi/IntroductionUiState.kt
gradle/libs.versions.toml

- 자기소개 API 호출순서 변경
- 자기소개 바텀 버튼 활성 상태 로직 수정
- 상대방 이미지 블러 효과 추가

[Release] 0.9.2-beta

---

README.md

[Docs] Read.me 작성

---

app/build.gradle.kts
app/src/main/java/com/team/bottles/MainActivity.kt
build-logic/build.gradle.kts
build-logic/src/main/kotlin/AndroidFirebaseConventionPlugin.kt
build.gradle.kts
core/common/src/main/kotlin/com/team/bottles/core/common/extension/UriExtension.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/IntroductionViewModel.kt
gradle/libs.versions.toml

- closed #63 
- Firebase 커스텀 플러그인 제작
- Crashlytics 설정
- Analytics 설정

[Feat] Firebase Crashlytics 및 Analytics 셋팅

---

feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/PingPongRoute.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/PingPongScreen.kt

[Feat] 핑퐁 화면 캡처 제한

---

core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/bars/BottomBar.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/buttons/SolidButton.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/popup/BalloonPopup.kt
feat/onboarding/src/main/kotlin/com/team/bottles/feat/onboarding/OnboardingScreen.kt
feat/sandbeach/src/main/kotlin/com/team/bottles/feat/sandbeach/SandBeachViewModel.kt

- closed #68
- 모래사장 상태 오류 수정
- 온보딩 버튼 클릭 영역 확장

[Fix] 모래사장 상태 오류 수정

---

feat/sandbeach/src/main/kotlin/com/team/bottles/feat/sandbeach/SandBeachRoute.kt
gradle/libs.versions.toml

- 핑퐁 화면 당겨서 새로고침 기능 추가
- 푸쉬 알림 기능 추가

[Release] 버전 업데이트 - 0.9.4-beta

---

app/src/main/java/com/team/bottles/MainActivity.kt
gradle/libs.versions.toml

[Release] 버전 업데이트 - 0.9.5-beta

---

app/src/main/java/com/team/bottles/di/usecase/AuthUseCaseModule.kt
app/src/main/java/com/team/bottles/di/usecase/UserUseCaseModule.kt
core/data/src/main/kotlin/com/team/bottles/core/data/mapper/UpdateAppVersionResponseMapper.kt
core/data/src/main/kotlin/com/team/bottles/core/data/repository/AuthRepositoryImpl.kt
core/data/src/main/kotlin/com/team/bottles/core/data/repository/UserRepositoryImpl.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/auth/repository/AuthRepository.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/auth/usecase/GetLatestAppVersionUseCase.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/user/repository/UserRepository.kt
core/domain/src/main/kotlin/com/team/bottles/core/domain/user/usecase/UpdateBlockingContactsUseCase.kt
core/network/src/main/kotlin/com/team/bottles/network/api/AuthService.kt
core/network/src/main/kotlin/com/team/bottles/network/api/UserService.kt
core/network/src/main/kotlin/com/team/bottles/network/datasource/AuthDataSource.kt
core/network/src/main/kotlin/com/team/bottles/network/datasource/AuthDataSourceImpl.kt
core/network/src/main/kotlin/com/team/bottles/network/datasource/UserDataSource.kt
core/network/src/main/kotlin/com/team/bottles/network/datasource/UserDataSourceImpl.kt
core/network/src/main/kotlin/com/team/bottles/network/di/NetworkModule.kt
core/network/src/main/kotlin/com/team/bottles/network/dto/auth/request/BlockContactListRequest.kt
core/network/src/main/kotlin/com/team/bottles/network/dto/auth/response/UpdateAppVersionResponse.kt
feat/mypage/build.gradle.kts
feat/mypage/src/main/kotlin/com/team/bottles/feat/mypage/MyPageRoute.kt
feat/mypage/src/main/kotlin/com/team/bottles/feat/mypage/MyPageScreen.kt
feat/mypage/src/main/kotlin/com/team/bottles/feat/mypage/MyPageViewModel.kt
feat/mypage/src/main/kotlin/com/team/bottles/feat/mypage/components/SettingList.kt
feat/mypage/src/main/kotlin/com/team/bottles/feat/mypage/mvi/MyPageSideEffect.kt
feat/mypage/src/main/kotlin/com/team/bottles/feat/mypage/mvi/MyPageUiState.kt

- 연락처 차단 기능 구현
- 앱 선택적 업데이트 기능 구현
- Json 설정 변경 (ignoreUnknowKeys = true)

[Feat] 마이페이지 - 연락처 차단, 앱 선택적 업데이트 기능 구현

---

README.md
feat/onboarding/src/main/kotlin/com/team/bottles/feat/onboarding/OnboardingScreen.kt
feat/sandbeach/src/main/kotlin/com/team/bottles/feat/sandbeach/SandBeachRoute.kt
gradle/libs.versions.toml

- 스플래쉬, 모래사장 화면에서 앱 강제 기능 추가
- 마이페이지에서 선택적 업데이트 기능 추가 
- 마이페이지 UI 변경
- 푸쉬 알림 설정 기능 추가
- 푸쉬 알림 아이콘 변경
- 연락처 차단 기능 추가
- 일부 디자인 컴포넌트 수정 
- 특정 기기의 앱 아이콘 배경이 안드로이드 기본 앱 배경으로 나오던 오류 수정

[Release] 버전 업데이트 - 1.0.0

---

app/src/main/java/com/team/bottles/BottlesApp.kt
app/src/main/java/com/team/bottles/MainActivity.kt
app/src/main/java/com/team/bottles/navigation/BottlesNavHost.kt
core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/bars/NavBar.kt
core/ui/src/main/kotlin/com/team/bottles/core/ui/WebView.kt
feat/bottle/build.gradle.kts
feat/bottle/src/main/kotlin/com/team/bottles/feat/bottle/arrivedbottles/ArrivedBottlesScreen.kt
feat/bottle/src/main/kotlin/com/team/bottles/feat/bottle/bottlebox/BottleBoxRoute.kt
feat/bottle/src/main/kotlin/com/team/bottles/feat/bottle/bottlebox/BottleBoxScreen.kt
feat/bottle/src/main/kotlin/com/team/bottles/feat/bottle/navigation/BottleNavigation.kt
feat/login/src/main/kotlin/com/team/bottles/feat/login/LoginScreen.kt
feat/login/src/main/kotlin/com/team/bottles/feat/login/component/BottomButtons.kt
feat/mypage/src/main/kotlin/com/team/bottles/feat/mypage/MyPageRoute.kt
feat/mypage/src/main/kotlin/com/team/bottles/feat/mypage/MyPageScreen.kt
feat/mypage/src/main/kotlin/com/team/bottles/feat/mypage/navigation/MyPageNavigation.kt
feat/onboarding/src/main/kotlin/com/team/bottles/feat/onboarding/OnboardingScreen.kt
feat/onboarding/src/main/kotlin/com/team/bottles/feat/onboarding/components/StepOne.kt
feat/onboarding/src/main/kotlin/com/team/bottles/feat/onboarding/components/StepThree.kt
feat/onboarding/src/main/kotlin/com/team/bottles/feat/onboarding/components/StepTwo.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/PingPongScreen.kt
feat/profile/build.gradle.kts
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/createprofile/CreateProfileScreen.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/edit/EditProfileScreen.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/introduction/IntroductionScreen.kt
feat/report/src/main/kotlin/com/team/bottles/feat/report/ReportScreen.kt
feat/sandbeach/src/main/kotlin/com/team/bottles/feat/sandbeach/SandBeachRoute.kt
feat/sandbeach/src/main/kotlin/com/team/bottles/feat/sandbeach/SandBeachScreen.kt
feat/sandbeach/src/main/kotlin/com/team/bottles/feat/sandbeach/navigation/SandBeachNavigation.kt
feat/setting/src/main/kotlin/com/team/bottles/feat/setting/account/AccountSettingScreen.kt
feat/setting/src/main/kotlin/com/team/bottles/feat/setting/notification/NotificationSettingScreen.kt

- #100 
- 전체 화면 영역 시스템 상단바 까지 확장
- 웹뷰 URL 파라미터 추가
- 웹뷰 화면 영역 확장
- 화면 전환 간 애니메이션 제거
- 일부 디자인 QA 적용

[Feat] 전체 화면 영역 확장 및 1차 디자인 QA 일부 반영

---

app/src/main/java/com/team/bottles/BottlesApplication.kt
core/common/build.gradle.kts
core/common/src/main/kotlin/com/team/bottles/core/common/BaseViewModel.kt

- 디버그 모드일 경우 파이어베이스 로그 수집 중지
- 예외 발생시 뷰모델에서 예외 수집

[Feat] 파이어베이스 Crashrytics 활성화 로직 및 예외 수집

---

gradle/libs.versions.toml

- 마이페이지 수정 기능 추가
- 연락처 권한 거부시 상세 안내 다이얼로그가 추가
- 매칭 활성화 기능 추가
- 에러 인터셉터 추가
- 에러 화면 추가
- 재시도 로직 구현
- 에러 안내 메세지 추가
- 파이어 베이스 크래시리틱스 활성화 로직 추가
- 파이어 베이스 예외 수집 로직 추가
- 화면 전환 애니메이션 삭제
- 전체 화면 영역 확장
- 웹뷰 딤머 대응을 위한 URL 파라미터 추가 (다음 버전 적용 예정)

[Release] 버전 업데이트 - 1.0.1

---

app/src/main/java/com/team/bottles/navigation/BottlesNavHost.kt
feat/bottle/src/main/kotlin/com/team/bottles/feat/bottle/navigation/BottleNavigation.kt
feat/mypage/src/main/kotlin/com/team/bottles/feat/mypage/navigation/MyPageNavigation.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/navigation/PingPongNavigation.kt
feat/profile/src/main/kotlin/com/team/bottles/feat/profile/navigation/ProfileNavigation.kt
feat/sandbeach/src/main/kotlin/com/team/bottles/feat/sandbeach/navigation/SandBeachNavigation.kt
feat/setting/src/main/kotlin/com/team/bottles/feat/setting/account/AccountSettingScreen.kt
feat/setting/src/main/kotlin/com/team/bottles/feat/setting/navigation/SettingNavigation.kt
feat/setting/src/main/kotlin/com/team/bottles/feat/setting/notification/NotificationSettingScreen.kt
gradle/libs.versions.toml

- Compose Navigation 버전 업데이트 2.8.0-beta06 -> 2.8.1
- 모래사장 <-> 도착한 보틀 애니메이션 구현
- 보틀 보관함 <-> 핑퐁 애니메이션 구현
- 마이페이지 <-> 프로필 수정, 계정관리, 알림설정 애니메이션 구현

[Feat] 메인 화면 애니메이션 구현

---

core/design-system/src/main/kotlin/com/team/bottles/core/designsystem/components/etc/menu/TabItem.kt
core/ui/src/main/kotlin/com/team/bottles/core/ui/RowTab.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/detail/PingPongDetailScreen.kt
feat/ping-pong/src/main/kotlin/com/team/bottles/feat/pingpong/detail/components/Topbar.kt

- #113 
- BottlesTabItem 컴포넌트 추가
- RowTab UI 변경
- 문답 상세 화면의 탭바 UI 변경

[Fix] 문답 상세 화면 탭바 UI 변경

---

gradle/libs.versions.toml

- 메인 화면의 '보틀 보관함' 탭 변경 #116 
- '문답' 탭으로 변경
- '문답' 화면의 리스트 UI 변경
- EmptyBottles UI 변경
- 진행중 / 완료 탭 삭제
- `bottle` 모듈의 `bottleBox` 패키지에서 `ping-pong` 모듈로 변경
- 기존의 PingPong 화면을 PingPongDetail로 변경
- 모듈 내 구조를 `PingPongScreen` 과 `PingPongDetail` 로 구현
- `PingPongDetailScreen`의 탭 UI 변경 (참고 PR : #115)
- '도착한 보틀' 웹뷰 변경 #117 
- '추천 보틀' 로 URL 변경
- '추천 보틀' 의 리스트에서 아이템 클릭시 보틀의 상세 화면으로 이동하는 로직 구현
- `recommendation` 모듈 추가
- 모듈 내 구조를 `RecommendationScreen` 과 `RecommendationDetailScreen` 로 구현
- 메인 화면의 '호감' 탭 추가 #115 
- 메인의 화면 상태 유지를 위한 `LocalLikeTabWebViewComposition` 생성 (참고 PR : #115)
- `like` 모듈 생성
- 모듈 내 구조를  `LikeScreen` 과 `LikeDetailScreen` 으로 구현
- 화면 전환 애니메이션 변경 #107 
- 메인에서 다른 화면으로 이동시 모든 `popBackStack` 때 `slideOut` 으로 적용
- 알림 권한 로직 변경 #114 
- 모래사장에서 알림 권한 요청 제거
- 로그인 화면 알림 권한 요청 추가
- 알림 설정 화면 알림 권한 …

[Release] 버전 업데이트 - 1.0.2

---

gradle/libs.versions.toml

- 로딩 UI 변경
- 프로필 이미지 수정시 Photo Picker를 활용해서 이미지 수정
- 시스템 알림 설정 여부 구현
- 문답 상세의 사진 교환 UI 변경
- 문답, 문답 상세에서 유저 이미지 없어지는 오류 수정
- 자기소개 작성 웹뷰로 변경
- 광고용 앱 링크 설정
- UserProfileResponse 데이터 필드 null-safety 적용

[Release] 버전 업데이트 - 1.0.3
